name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install invoke
          invoke install
      - name: lint (black)
        run: |
          invoke presubmit.black
      - name: lint (isort)
        run: |
          invoke presubmit.isort
      - name: type check
        run: |
          invoke presubmit.mypy
      - name: run unit tests
        run: |
          invoke presubmit.pytest
