name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt stopwords
      - name: lint (black)
        run: |
          python -m black --check src
      - name: lint (isort)
        run: |
          isort -c scripts src
      - name: type check
        run: |
          mypy scripts src
      - name: run unit tests
        run: |
          pytest tests
